apiVersion: v1
kind: Deployment
metadata:
 name: spotme-rest
 labels:
    app: spotme-rest
    type: back-end
    project: spotme
spec:
  template:
    containers:
    - name: spotme-rest
      image: "http://containerregistry.spot-me-app.com/artifactory/spotme/spotme-rest/latest"
  replicas: 2


