apiVersion: v1
kind: ConfigMap
metadata:
  name: spotme-config
data:
  db_url: "jdbc:mysql://192.168.1.238:30206/spotme_local?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  db_behavior: "update"
  db_driver: "com.mysql.cj.jdbc.Driver"
  db_dialect: "org.hibernate.dialect.MySQLDialect"
  custom_port: "8081"
  origin: "https://rest-dev.spot-me-app.com"
  ui_origin: "https://ui-dev.spot-me-app.com"
  dev_url: "https://rest-dev.spot-me-app.com"
  prod_url: "https://rest-dev.spot-me-app.com"
