apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotme-db
  namespace: spotme-dev
  labels:
    app: spotme-db
spec:
  selector:
    matchLabels:
      app: spotme-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spotme-db
    spec:
      containers:
        - image: mysql:8.0-debian
          name: spotme-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spotme-app-secrets
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spotme-app-secrets
                  key: username
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: spotme-mysql-storage-dev
              mountPath: /var/lib/mysql
      volumes:
        - name: spotme-mysql-storage-dev
          persistentVolumeClaim:
            claimName: spotme-mysql-pvc-dev
